'use client';
import './globals.css'

import { Providers } from '@/redux/provider'
import store from '@/redux/services/store'

export const metadata = {
  title: 'Workables - App',
  description: 'Generated by create next app',
}

import { usePathname } from 'next/navigation'
import { useState, } from 'react';
import { useSelector } from 'react-redux';
import Header from '../../components/header/Header'
import Footer from '../../components/footer/Footer'
import { Questrial } from '@next/font/google'

const questrial = Questrial({
  subsets:['latin'],
  weight:['400']
})

export default function RootLayout({ children }) {

  const [fixed, setFixed] = useState(false)
  const params = usePathname()
  // const fixed = useSelector(state => state.fixed)

  return (
    <Providers store={store}>
      <html lang="en">
      <body className={`${questrial.className} bg-[url('../../public/Backgrounds.webp')] bg-cover bg-no-repeat ${fixed ? 'overflow-hidden' : ''} `}>
        <Header fixed={fixed} setFixed={setFixed} />
          {/* <head>
            <title>Workables - App</title>
            <meta name="description" content="Generated by create next app"/>
          </head> */}
          {children}
          <Footer />
      </body>
      </html>
    </Providers>
  )
}
