'use client';
import './globals.css'

import { Providers } from '@/redux/provider'
import store from '@/redux/services/store'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <Providers store={store}>
      <html lang="en">
        <head>
          <title>Workables - App</title>
          <meta name="description" content="Generated by create next app"/>
        </head>
          {children}
      </html>
    </Providers>
  )
}
